import Footer from "@/views/footer/Footer";
import Navbar from "@/views/navbar/Navbar";
import Head from "next/head";

const Terms = () => {
  return (
    <>
      <Head>
        <title>Terms and Conditions - Habitat Plush</title>
        <meta
          name="description"
          content="Terms and Conditions for Habitat Plush services"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <div className="max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
        <div className="">
          <h1 className="text-3xl font-bold text-center text-blue-600">
            Terms and Conditions
          </h1>

          <p className="mt-4 text-lg leading-7 text-gray-700">
            Welcome to the Habitat Plush Society Management software (web portal
            and Mobile app), a platform designed to streamline housing society
            management. By accessing or using our Web App and/or Mobile App, you
            agree to comply with and be bound by these Terms and Conditions. If
            you do not agree to these terms, you may not use the App.
          </p>

          <p className="mt-4 text-lg leading-7 text-gray-700">
            This document is an electronic record generated by a computer system
            and does not require physical or digital signatures.
          </p>

          <p className="mt-4 text-lg leading-7 text-gray-700">
            We urge you to carefully review the following Terms and Conditions.
            They include critical information regarding your rights,
            responsibilities, and any applicable limitations or exclusions.
          </p>

          <p className="mt-4 text-lg leading-7 text-gray-700">
            By accessing or using our website, https://habitatplush.com/
            (“Website”), or the Habitat Plush mobile application (“App”)
            (collectively referred to as the “Platform”), you acknowledge and
            agree to abide by these terms (“Terms of Use” or “Terms”).
          </p>

          <p className="mt-4 text-lg leading-7 text-gray-700">
            Please ensure you read these Terms and Conditions thoroughly before
            registering on the App or using the Platform.
          </p>

          <section className="mt-8">
            <h2 className="text-2xl font-semibold text-gray-900">Contents</h2>
            <ol className="list-decimal list-inside mt-4 text-gray-700">
              <li>Product License</li>
              <li>Payment</li>
              <li>Restrictions on Usage of this Product</li>
              <li>Customer Data</li>
              <li>Representations and Warranties</li>
              <li>Availability of Services and Warranty limitations</li>
              <li>Integration to Third party Website and Services</li>
              <li>Confidential Information</li>
              <li>Data Protection and Security</li>
              <li>Intellectual Property Rights</li>
              <li>Compliance with Laws</li>
              <li>Term and Termination</li>
              <li>Indemnification</li>
              <li>Publicity</li>
              <li>Force majeure</li>
              <li>Limitation of Liability</li>
              <li>Dispute Resolution</li>
              <li>Agreement</li>
              <li>Notice Clause</li>
              <li>Support Services Clause</li>
            </ol>
          </section>

          <section className="mt-8">
            <h2 className="text-2xl font-semibold text-gray-900">Acceptance</h2>
            <p className="mt-4 text-gray-700">
              By accessing or using Habitat Plush’s services, including its web
              portal, mobile app(s), and APIs (collectively referred to as
              “Habitat Plush”), you agree to be bound by these Terms and
              Conditions.
            </p>
            <p className="mt-4 text-gray-700">
              You must use the platform only for lawful purposes and in
              compliance with these Terms. This agreement forms a legally
              binding contract between you and Habitat Plush.
            </p>
            <p className="mt-4 text-gray-700">
              To accept these Terms, you must be at least 18 years old. If you
              are under 18, a guardian must review, understand, and accept these
              Terms on your behalf. If you are accepting these Terms on behalf
              of a registered association, society, or builder, you confirm that
              you are of legal age and authorized to do so.
            </p>
            <p className="mt-4 text-gray-700">
              You also agree to provide accurate and complete information about
              yourself and update it promptly if any changes occur.
            </p>
            <p className="mt-4 text-gray-700">
              By using the Habitat Plush platform, you acknowledge and accept
              these Terms, Conditions, and disclaimers. If you do not agree, you
              must stop using the platform immediately.
            </p>
          </section>

          <section className="mt-8">
            <h2 className="text-2xl font-semibold text-gray-900">
              Terms of Subscription
            </h2>
            <p className="mt-4 text-gray-700">
              This Terms of Subscription (“Agreement”) is entered into between
              Habitat Plush (“Service Provider”) and you, or the entity you
              represent (“Customer/Supplier”), governing your access to and use
              of the Service Provider’s products and services (“Product”). If
              you are acting on behalf of an entity, you confirm that you have
              obtained all necessary approvals and authorization to bind the
              entity to this Agreement.
            </p>
            <p className="mt-4 text-gray-700">
              The Service Provider and Customer are individually referred to as
              a “Party/Buyer” and collectively as the “Parties/Buyers.”
            </p>
            <p className="mt-4 text-gray-700">
              The terms of this Agreement, including payment obligations, shall
              be governed by the agreed or granted Order Form executed between
              the Service Provider (“Supplier”) and the “Buyer” or “Buyers.” The
              Supplier hereby grants the Buyer access to the Product as
              specified in the Order Form.
            </p>
          </section>

          <section className="mt-8">
            <h2 className="text-2xl font-semibold text-gray-900">
              1. Product License
            </h2>
            <ul className="list-inside list-disc mt-4 text-gray-700">
              <li>
                The Service Provider grants the Customer a subscription to the
                Product under the following conditions:
              </li>
              <ul className="list-inside list-disc mt-2 text-gray-700">
                <li>
                  Non-exclusive: Access is limited to the Customer without
                  exclusivity.
                </li>
                <li>
                  Non-transferable: The subscription cannot be transferred to
                  another entity.
                </li>
                <li>
                  Non-sublicensable: The Customer cannot sublicense the Product.
                </li>
                <li>
                  Limited and restricted: Usage is confined to the scope defined
                  in this Agreement.
                </li>
                <li>
                  Revocable: Access can be withdrawn if terms are violated.
                </li>
              </ul>
              <li>
                Access and use of the Product are solely for availing the
                Service Provider’s services and are subject to the payment of
                fees as specified in the Order Form.
              </li>
              <li>An Order Form will be executed by the Parties to outline:</li>
              <ul className="list-inside list-disc mt-2 text-gray-700">
                <li>The services to be provided.</li>
                <li>The applicable terms and conditions.</li>
                <li>
                  Any conflict between this Agreement and the Order Form will
                  prioritize the terms of the Order Form.
                </li>
              </ul>
              <li>
                The Customer is responsible for ensuring that its employees,
                users, account managers, or other personnel using the Product
                comply with the terms and conditions of this Agreement.
              </li>
            </ul>
          </section>

          <section className="mt-8">
            <h2 className="text-2xl font-semibold text-gray-900">2. Payment</h2>
            <ul className="list-inside list-disc mt-4 text-gray-700">
              <li>
                The Customer agrees to pay the Service Provider the fees
                specified in the respective Order Form accepted by the Customer,
                in consideration for the Services and the usage of the Product.
                The Service Provider is authorized to issue invoices in
                accordance with the terms outlined in the Order Form.
              </li>
              <li>
                Payments shall be made within the stipulated time mentioned in
                the Order Form.
              </li>
              <li>In the event of non-payment within the agreed timeline:</li>
              <ul className="list-inside list-disc mt-2 text-gray-700">
                <li>
                  The Service Provider reserves the right to discontinue
                  Services to the Customer.
                </li>
                <li>
                  The Service Provider may suspend the access of the Customer or
                  its personnel to the Product until the dues are cleared.
                </li>
              </ul>
              <li>
                Timely payment is essential for the continuation of Services
                under this Agreement.
              </li>
            </ul>
          </section>

          <section className="mt-8">
            <h2 className="text-2xl font-semibold text-gray-900">
              3. Restrictions on Usage of this Product
            </h2>
            <p className="mt-4 text-gray-700">
              The Customer represents and warrants that:
            </p>
            <ul className="list-inside list-disc mt-4 text-gray-700">
              <li>
                <strong>Restrictions on Use:</strong>
              </li>
              <ul className="list-inside list-disc mt-2 text-gray-700">
                <li>
                  The Customer shall not rent, lease, distribute, license,
                  sublicense, sell, resell, assign, transfer, timeshare, or
                  otherwise make the Product available to any third party in
                  violation of the terms stated in this Agreement.
                </li>
                <li>
                  The Customer shall not reverse engineer, de-compile,
                  disassemble, or attempt to discover the source code or
                  underlying ideas or algorithms of the Product.
                </li>
                <li>
                  The Customer shall not access the Product for the purpose of
                  building a commercially available product or service that
                  competes with the Product.
                </li>
                <li>
                  The Customer shall not copy any features, functions,
                  integrations, interfaces, or graphics that are part of the
                  Product.
                </li>
              </ul>
              <li>
                <strong>Truthfulness and Legality of Information:</strong>
              </li>
              <ul className="list-inside list-disc mt-2 text-gray-700">
                <li>
                  The Customer shall ensure that all information provided to the
                  Service Provider is true, accurate, and lawfully obtained as
                  per applicable laws.
                </li>
              </ul>
              <li>
                <strong>Prohibited Actions:</strong>
              </li>
              <ul className="list-inside list-disc mt-2 text-gray-700">
                <li>
                  The Customer shall not damage, disable, overburden, or impair
                  the Service Provider’s servers or network, nor interfere with
                  any other party’s use and enjoyment of the Product.
                </li>
                <li>
                  The Customer shall not knowingly tamper with the security of
                  the Product, including attempting to probe, scan, or test the
                  vulnerability of the Product or breach its security or
                  authentication measures.
                </li>
              </ul>
              <li>
                <strong>Compliance with Laws:</strong>
              </li>
              <ul className="list-inside list-disc mt-2 text-gray-700">
                <li>
                  The Customer shall not use the Product in any manner that is
                  prohibited by applicable law or regulation.
                </li>
              </ul>
              <li>
                <strong>Prohibited Content:</strong>
              </li>
              <ul className="list-inside list-disc mt-2 text-gray-700">
                <li>
                  The Customer or its personnel shall not transmit or use the
                  Product to transmit:
                </li>
                <ul className="list-inside list-disc mt-2 text-gray-700">
                  <li>
                    Any content that is unlawful, threatening, abusive,
                    libelous, or defamatory.
                  </li>
                  <li>
                    Any information contrary to the provisions of this
                    Agreement.
                  </li>
                  <li>
                    Spam, including unauthorized or unsolicited advertising,
                    chain letters, lotteries, or gambling-related content.
                  </li>
                  <li>
                    Content that violates the privacy rights of any third party.
                  </li>
                </ul>
                <li>
                  The Customer shall not host, display, upload, modify, publish,
                  transmit, update, or share any information belonging to
                  another person without the legal right to do so.
                </li>
              </ul>
            </ul>
            <p className="mt-4 text-gray-700">
              Failure to comply with these representations and warranties may
              result in immediate suspension or termination of access to the
              Product, at the Service Provider's sole discretion.
            </p>
          </section>

          <section className="mt-8">
            <h2 className="text-2xl font-semibold text-gray-900">
              4. Customer Data
            </h2>
            <p className="mt-4 text-gray-700">
              <strong>Ownership of Customer Data:</strong>
              The Customer retains ownership of all information, data, and
              material generated, uploaded, accessed, interpreted, or analyzed
              through the Product (collectively referred to as “Customer Data”).
            </p>
            <p className="mt-4 text-gray-700">
              <strong>No Obligation to Review:</strong>
              The Service Provider is not obligated to review Customer Data for
              accuracy or potential liability.
            </p>
            <p className="mt-4 text-gray-700">
              <strong>Indemnification:</strong>
              The Customer agrees to fully indemnify, defend, and hold the
              Service Provider harmless from any damages, losses, costs, or
              liabilities arising from or related to Customer Data.
            </p>
          </section>

          <section className="mt-8">
            <h2 className="text-2xl font-semibold text-gray-900">
              5. Representations and Warranties
            </h2>
            <p className="mt-4 text-gray-700">
              <strong>Legal Authority:</strong>
              Each Party confirms it has the legal right and authority to enter
              into this Agreement and fulfill its obligations as outlined.
            </p>
            <p className="mt-4 text-gray-700">
              <strong>Authorized Representation:</strong>
              Representatives executing this Agreement, whether electronically
              or physically, are duly authorized to bind their respective
              Parties.
            </p>
            <p className="mt-4 text-gray-700">
              <strong>Regulatory Compliance:</strong>
              Both Parties agree to adhere to all applicable legal and
              regulatory requirements relevant to exercising their rights and
              fulfilling their obligations under this Agreement.
            </p>
          </section>

          <section className="mt-8">
            <h2 className="text-2xl font-semibold text-gray-900">
              6. Availability of Services and Warranty Limitations
            </h2>
            <p className="mt-4 text-gray-700">
              <strong>No Warranty:</strong> The Service Provider and its
              representatives make no express, implied, or statutory warranties,
              including but not limited to:
            </p>
            <ul className="list-inside list-disc mt-4 text-gray-700">
              <li>Accuracy of the Product.</li>
              <li>Merchantability or fitness for a particular purpose.</li>
              <li>
                Title, enforceability, or non-infringement of the Product.
              </li>
            </ul>
            <p className="mt-4 text-gray-700">
              <strong>Software Limitations:</strong> The Customer acknowledges
              that complex software is inherently prone to defects, errors, and
              bugs in design, functionality, security, and other aspects. The
              Service Provider does not guarantee the Product will be entirely
              free from such issues.
            </p>
            <p className="mt-4 text-gray-700">
              <strong>Compatibility:</strong> The Product is warranted to be
              compatible only with software and systems specified by the Service
              Provider. No guarantees are made for compatibility with other
              software or systems.
            </p>
            <p className="mt-4 text-gray-700">
              <strong>Functionality Assurance:</strong> The Service Provider
              ensures that the Product’s functionality will not materially
              decrease during the active Subscription Term.
            </p>
            <p className="mt-4 text-gray-700">
              <strong>Subscription Term Definition:</strong> The Subscription
              Term refers to the period covered by the payment already made for
              the Product subscription.
            </p>
            <p className="mt-4 text-gray-700">
              <strong>Remedy for Breach:</strong> In the event of a warranty
              breach, the Customer’s sole remedy will be:
            </p>
            <ul className="list-inside list-disc mt-4 text-gray-700">
              <li>Termination of the Subscription.</li>
              <li>
                Refund of advance payments made for the remaining Subscription
                Term.
              </li>
            </ul>
          </section>

          <section className="mt-8">
            <h2 className="text-2xl font-semibold text-gray-900">
              7. Integration to Third Party Website and Services
            </h2>
            <p className="mt-4 text-gray-700">
              <strong>Third-Party Software and Hardware Integrations:</strong>{" "}
              The Service Provider will exercise due diligence when selecting
              third-party software or hardware for Product integration. However,
              the Service Provider does not guarantee:
            </p>
            <ul className="list-inside list-disc mt-4 text-gray-700">
              <li>Error-free functioning of such integrations.</li>
              <li>
                Continuity of services provided by the third-party software or
                hardware.
              </li>
            </ul>
            <p className="mt-4 text-gray-700">
              <strong>Third-Party Website Links:</strong> The Service Provider’s
              website may include links to third-party websites managed by
              external entities. These links do not constitute endorsements of
              the linked websites or their services. The Customer acknowledges
              and agrees that the Service Provider:
            </p>
            <ul className="list-inside list-disc mt-4 text-gray-700">
              <li>
                Is not responsible for the content, functionality, or
                availability of these third-party websites or services.
              </li>
            </ul>
          </section>

          <section className="mt-8">
            <h2 className="text-2xl font-semibold text-gray-900">
              8. Confidential Information
            </h2>
            <p className="mt-4 text-gray-700">
              <strong>Definition:</strong> Each Party may disclose to the other
              certain non-public, proprietary, or sensitive information, whether
              or not explicitly labelled as "confidential," related to business
              activities, including technical, marketing, financial, and
              planning data (“Confidential Information”).
            </p>
            <p className="mt-4 text-gray-700">
              <strong>Obligations of the Receiving Party:</strong> The Receiving
              Party must:
            </p>
            <ul className="list-inside list-disc mt-4 text-gray-700">
              <li>Hold Confidential Information in trust and confidence.</li>
              <li>
                Avoid disclosing such information to any third party unless
                authorized in writing by the Disclosing Party or as specified in
                this Agreement.
              </li>
            </ul>
            <p className="mt-4 text-gray-700">
              <strong>Disclosure Required by Law:</strong> Confidential
              Information may be disclosed if legally required, provided that:
            </p>
            <ul className="list-inside list-disc mt-4 text-gray-700">
              <li>
                The Receiving Party gives prior written notice to the Disclosing
                Party (when feasible) to seek protective measures.
              </li>
              <li>
                The disclosed information is limited to what is reasonably
                necessary to comply with the legal requirement.
              </li>
            </ul>
            <p className="mt-4 text-gray-700">
              <strong>Exclusions from Confidential Information:</strong>{" "}
              Information will not be considered “Confidential Information” if:
            </p>
            <ul className="list-inside list-disc mt-4 text-gray-700">
              <li>
                It was already known to the Receiving Party without restrictions
                before disclosure by the Disclosing Party.
              </li>
              <li>
                It is obtained from a third party without confidentiality
                obligations or breach of agreements.
              </li>
              <li>
                It becomes publicly available through no wrongful act of the
                Receiving Party.
              </li>
              <li>
                It is independently developed by the Receiving Party without
                reference to the Confidential Information.
              </li>
            </ul>
            <p className="mt-4 text-gray-700">
              <strong>
                Return or Destruction of Confidential Information:
              </strong>{" "}
              Upon termination of this Agreement or at the Disclosing Party’s
              request, the Receiving Party must:
            </p>
            <ul className="list-inside list-disc mt-4 text-gray-700">
              <li>
                Either return all Confidential Information, documents, data, and
                related materials.
              </li>
              <li>
                Or destroy or permanently erase all such information and provide
                written confirmation of destruction, if requested.
              </li>
            </ul>
            <p className="mt-4 text-gray-700">
              <strong>Survival of Confidentiality:</strong> The confidentiality
              obligations under this Agreement will survive for two (2) years
              after its termination.
            </p>
          </section>

          <section className="mt-8">
            <h2 className="text-2xl font-semibold text-gray-900">
              9. Data Protection and Security
            </h2>
            <p className="mt-4 text-gray-700">
              <strong>Compliance with Data Protection Laws:</strong> Both
              Parties agree to comply with all applicable data protection laws
              concerning the collection, processing, and safeguarding of
              personal data.
            </p>
            <p className="mt-4 text-gray-700">
              <strong>Customer Account Responsibility:</strong> Customers are
              responsible for maintaining the confidentiality of their user IDs
              and passwords. Customers bear full responsibility for any
              activities conducted under their accounts.
            </p>
            <p className="mt-4 text-gray-700">
              <strong>Consent for Personal Data Sharing:</strong> The Customer
              represents and warrants that they have obtained prior written
              consent from individuals whose personal data is shared with the
              Service Provider.
            </p>
            <p className="mt-4 text-gray-700">
              <strong>Service Provider Obligations:</strong> The Service
              Provider acknowledges that any personal data shared by the
              Customer will only be processed per the terms outlined in the Data
              Processing Agreement (“DPA”). The DPA is made available to the
              Customer at the designated location.
            </p>
          </section>

          <section className="mt-8">
            <h2 className="text-2xl font-semibold text-gray-900">
              10. Intellectual Property Rights
            </h2>
            <p className="mt-4 text-gray-700">
              <strong>Ownership by Service Provider:</strong> The Service
              Provider retains all rights, title, and interest in the
              intellectual property rights related to the Product and Services,
              including:
            </p>
            <ul className="list-inside list-disc mt-4 text-gray-700">
              <li>Software, formats, interfaces, and data.</li>
              <li>
                Proprietary information and technology used or provided in
                connection with the Services or Product.
              </li>
              <li>
                Feedback, suggestions, ideas, enhancement requests, or other
                input from the Customer regarding the Services or Product.
              </li>
            </ul>
            <p className="mt-4 text-gray-700">
              These rights are protected under applicable intellectual property
              laws and are owned by or licensed to the Service Provider.
            </p>
            <p className="mt-4 text-gray-700">
              <strong>Customer's Usage Rights:</strong> The Customer is granted
              a limited, non-transferable license to use the Services and
              Product as explicitly stated in this Agreement. No other licenses
              or proprietary rights are granted. All rights not expressly
              provided to the Customer under this Agreement are reserved by the
              Service Provider.
            </p>
            <p className="mt-4 text-gray-700">
              <strong>
                Service Provider's Intellectual Property Development:
              </strong>{" "}
              The Service Provider owns all intellectual property rights for
              inventions, processes, algorithms, designs, software, or other
              creations ("Creatives") developed during the provision of
              Services. The Customer has no claim to such intellectual property,
              regardless of its association with the Services or Product.
            </p>
            <p className="mt-4 text-gray-700">
              <strong>Customer's Obligations:</strong> The Customer must take
              steps to prevent infringement of the Service Provider's
              copyrights, trademarks, or other intellectual property rights by
              third parties. Upon discovery of any actual or potential
              infringement, the Customer must:
            </p>
            <ul className="list-inside list-disc mt-4 text-gray-700">
              <li>Promptly inform the Service Provider.</li>
              <li>
                Cooperate with the Service Provider in instituting necessary
                actions to prevent or address the infringement.
              </li>
            </ul>
            <p className="mt-4 text-gray-700">
              <strong>Third-Party Infringement:</strong> If the Customer becomes
              aware of any third-party infringement or potential infringement
              related to the Product, the Customer must:
            </p>
            <ul className="list-inside list-disc mt-4 text-gray-700">
              <li>Notify the Service Provider immediately.</li>
              <li>
                Assist the Service Provider in taking appropriate legal or
                corrective measures as reasonably required.
              </li>
            </ul>
          </section>

          <section className="mt-8">
            <h2 className="text-2xl font-semibold text-gray-900">
              11. Compliance with Laws
            </h2>
            <p className="mt-4 text-gray-700">
              <strong>General Compliance:</strong> Each Party agrees to comply,
              at all times and at its own expense, with all applicable laws,
              regulations, and legal requirements that pertain to its
              performance under this Agreement.
            </p>
            <p className="mt-4 text-gray-700">
              <strong>Payment of Fees:</strong> Each Party is responsible for
              paying all applicable fees, charges, and expenses required by such
              laws or regulatory frameworks.
            </p>
            <p className="mt-4 text-gray-700">
              <strong>Licenses and Permits:</strong> Each Party must obtain,
              maintain, and keep in full force all necessary licenses, permits,
              authorizations, registrations, and qualifications required by
              regulatory authorities. This obligation is essential to ensure the
              Party's lawful ability to fulfill its commitments and obligations
              under this Agreement.
            </p>
          </section>

          <section className="mt-8">
            <h2 className="text-2xl font-semibold text-gray-900">
              12. Term and Termination
            </h2>
            <p className="mt-4 text-gray-700">
              <strong>Effective Date and Duration:</strong> This Agreement is
              valid from the Subscription Start Date (as defined in the Order
              Form) and continues until explicitly terminated.
            </p>
            <p className="mt-4 text-gray-700">
              <strong>Review and Termination:</strong> Either Party may review
              or terminate the Agreement at any time during the Subscription
              Term by providing at least thirty (30) days' written notice.
            </p>
            <p className="mt-4 text-gray-700">
              The Customer’s data will be available for extraction during the
              notice period, which must fall within the Subscription Paid
              Duration. After the notice period, access to the software will be
              discontinued.
            </p>
            <p className="mt-4 text-gray-700">
              The Service Provider will retain the Customer's data for ninety
              (90) days after termination in case of reactivation, subject to
              payment of the reactivation fee. After ninety (90) days, the
              Service Provider will delete the Customer data unless legally
              prohibited.
            </p>
            <p className="mt-4 text-gray-700">
              <strong>Non-Payment and Termination:</strong> Non-payment of the
              Subscription dues by the due date will result in automatic
              termination of the Subscription, and the Customer's access to the
              Services will be discontinued.
            </p>
            <p className="mt-4 text-gray-700">
              Upon termination, the Service Provider will revoke all rights
              granted under this Agreement.
            </p>
            <p className="mt-4 text-gray-700">
              <strong>Liabilities on Termination:</strong> Upon termination, the
              Customer is liable to pay for all Services availed and Product
              usage up to the termination date.
            </p>
            <p className="mt-4 text-gray-700">
              <strong>Breach of Terms:</strong> The Service Provider reserves
              the right to suspend the Customer’s usage of the Product and
              Services immediately in case of a breach of this Agreement by the
              Customer.
            </p>
          </section>

          <section className="mt-8">
            <h2 className="text-2xl font-semibold text-gray-900">
              13. Indemnification
            </h2>
            <p className="mt-4 text-gray-700">
              <strong>Service Provider's Indemnity:</strong> The Service
              Provider agrees to indemnify, defend, and hold harmless the
              Customer, its directors, officers, and employees from any losses,
              liabilities, claims, damages, costs, and expenses (including
              reasonable legal fees) resulting from:
            </p>
            <ul className="list-inside list-disc mt-4 text-gray-700">
              <li>Breach of applicable laws.</li>
              <li>
                Gross negligence or willful misconduct by the Service Provider.
              </li>
            </ul>
            <p className="mt-4 text-gray-700">
              The Service Provider also agrees to indemnify the Customer against
              any third-party claims or losses arising from infringement of
              intellectual property rights due to the use of the Product by the
              Customer.
            </p>
            <p className="mt-4 text-gray-700">
              <strong>Exceptions to Service Provider's Liability:</strong> The
              Service Provider will not be liable for indemnification if the
              claim arises from:
            </p>
            <ul className="list-inside list-disc mt-4 text-gray-700">
              <li>
                The combination or use of the Product with equipment or software
                supplied by the Customer, where the Product itself would not be
                infringing.
              </li>
              <li>
                Compliance with designs or instructions provided by the
                Customer.
              </li>
              <li>
                Use of the Product in an application or environment for which it
                was not designed or contemplated.
              </li>
            </ul>
            <p className="mt-4 text-gray-700">
              <strong>Customer's Indemnity:</strong> The Customer agrees to
              indemnify, defend, and hold harmless the Service Provider, its
              directors, officers, and employees from any losses, liabilities,
              claims, damages, costs, and expenses (including legal fees)
              arising from:
            </p>
            <ul className="list-inside list-disc mt-4 text-gray-700">
              <li>Infringement of intellectual property rights.</li>
              <li>Breach of applicable laws by the Customer.</li>
            </ul>
            <p className="mt-4 text-gray-700">
              <strong>Indemnification Process:</strong> The indemnification is
              conditional upon the Indemnified Party:
            </p>
            <ul className="list-inside list-disc mt-4 text-gray-700">
              <li>
                Notifying the Indemnifying Party in writing and promptly of the
                third-party claim.
              </li>
              <li>
                Authorizing the Indemnifying Party to conduct any judicial
                proceedings with the third party.
              </li>
              <li>
                Providing reasonable assistance (at the Indemnifying Party's
                expense) to defend such claims.
              </li>
            </ul>
          </section>

          <section className="mt-8">
            <h2 className="text-2xl font-semibold text-gray-900">
              14. Publicity
            </h2>
            <p className="mt-4 text-gray-700">
              Neither Party shall have the permission to use the name and logo
              of the other Party without the prior consent of the other Party.
            </p>
            <p className="mt-4 text-gray-700">
              <strong>Service Provider's Use of Customer's Logo:</strong> The
              Service Provider shall have the permission to use the Customer’s
              logo in identifying the Customer as a client of the Service
              Provider.
            </p>
          </section>

          <section className="mt-8">
            <h2 className="text-2xl font-semibold text-gray-900">
              15. Force Majeure
            </h2>
            <p className="mt-4 text-gray-700">
              <strong>Definition:</strong> A Force Majeure Event refers to any
              event or circumstance beyond the reasonable control of either
              Party that prevents or delays the performance of any of its
              obligations under this Agreement. These events include, but are
              not limited to:
            </p>
            <ul className="list-inside list-disc mt-4 text-gray-700">
              <li>Acts of God (e.g., earthquakes, hurricanes).</li>
              <li>Fire or casualty.</li>
              <li>Pandemic or epidemic.</li>
              <li>Floods or other natural disasters.</li>
              <li>War or terrorist acts.</li>
              <li>Failure of public utilities.</li>
              <li>Injunctions or governmental orders.</li>
              <li>Labour or civic unrest.</li>
              <li>Destruction of production facilities.</li>
            </ul>
            <p className="mt-4 text-gray-700">
              <strong>Obligation to Notify:</strong> If a Force Majeure Event
              occurs, the affected Party must immediately notify the other Party
              of the event. The notification should include details of the event
              and its impact on performance.
            </p>
            <p className="mt-4 text-gray-700">
              <strong>Duty to Mitigate:</strong> The affected Party shall make
              reasonable efforts to resume performance as soon as possible and
              take all necessary actions to mitigate the effects of the Force
              Majeure Event.
            </p>
          </section>

          <section className="mt-8">
            <h2 className="text-2xl font-semibold text-gray-900">
              16. Limitation of Liability
            </h2>
            <p className="mt-4 text-gray-700">
              <strong>Aggregate Liability:</strong> Excluding specific
              liabilities outlined below, each Party’s total liability under or
              in connection with this Agreement, whether arising from tort or
              contract, shall be limited to the actual direct damages incurred.
              Such liability shall not exceed the amount paid by the Customer to
              the Service Provider in the three (3) months immediately preceding
              the date of the formal written notice of the claim.
            </p>
            <p className="mt-4 text-gray-700">
              <strong>Exclusions from Limitation:</strong> The limitation stated
              above shall not apply to:
            </p>
            <ul className="list-inside list-disc mt-4 text-gray-700">
              <li>Indemnification obligations outlined in this Agreement.</li>
              <li>Acts of fraud or criminal liability.</li>
              <li>Gross negligence or willful misconduct.</li>
              <li>Death or personal injury.</li>
              <li>Damage to property.</li>
              <li>
                Breaches of the terms and conditions stated in this Agreement.
              </li>
            </ul>
            <p className="mt-4 text-gray-700">
              <strong>Exclusion of Consequential Damages:</strong> Neither Party
              shall be liable to the other for any consequential, indirect,
              special, punitive, or incidental damages (including but not
              limited to lost profits, loss of data, or business interruption),
              regardless of the form of action or theory of recovery, even if
              advised of the possibility of such damages.
            </p>
          </section>

          <section className="mt-8">
            <h2 className="text-2xl font-semibold text-gray-900">
              17. Dispute Resolution
            </h2>
            <p className="mt-4 text-gray-700">
              <strong>Mutual Discussion:</strong> Any dispute arising out of or
              in relation to this Agreement shall first be addressed through
              mutual discussion between the Customer and the Service Provider in
              good faith, with the aim of reaching an amicable resolution.
            </p>
            <p className="mt-4 text-gray-700">
              <strong>Unresolved Disputes:</strong> If the dispute cannot be
              resolved through mutual discussion:
            </p>
            <p className="mt-4 text-gray-700">
              For Customers residing in India, the dispute shall be referred to
              the Courts of Bangalore, Karnataka, India, which shall have
              exclusive jurisdiction.
            </p>
            <p className="mt-4 text-gray-700">
              <strong>Arbitration:</strong> If the Parties agree to arbitration
              as a method for resolving the dispute, the following terms shall
              apply:
            </p>
            <ul className="list-inside list-disc mt-4 text-gray-700">
              <li>
                The arbitration shall be conducted in accordance with the
                applicable arbitration laws of India.
              </li>
              <li>The language of arbitration shall be English.</li>
              <li>
                The decision of the arbitrator(s) shall be final and binding on
                both Parties.
              </li>
            </ul>
          </section>

          <section className="mt-8">
            <h2 className="text-2xl font-semibold text-gray-900">
              18. Agreement
            </h2>
            <p className="mt-4 text-gray-700">
              <strong>Complete Understanding:</strong> This Agreement, including
              the Order Form and any annexures, schedules, or exhibits referred
              to and attached herein, represents the entire understanding
              between the Parties. It supersedes all prior agreements, promises,
              representations, negotiations, or understandings, whether written
              or oral, related to its subject matter.
            </p>
            <p className="mt-4 text-gray-700">
              <strong>Modifications:</strong> Any modifications, amendments, or
              supplements to this Agreement must be documented in writing and
              signed by authorized representatives of both Parties to be legally
              binding.
            </p>
            <p className="mt-4 text-gray-700">
              <strong>Non-Waiver:</strong> The failure or delay by either Party
              to enforce any provision, exercise an option, or demand
              performance shall not be construed as a waiver of any rights or
              remedies under this Agreement.
            </p>
            <p className="mt-4 text-gray-700">
              <strong>Severability:</strong> If any term, provision, or part of
              this Agreement is found to be invalid, void, or unenforceable, the
              remainder of the Agreement shall remain valid and enforceable to
              the fullest extent permitted by law.
            </p>
            <p className="mt-4 text-gray-700">
              <strong>Survival:</strong> Provisions of this Agreement that, by
              their nature, require performance or observance after termination
              or expiration shall remain in effect and continue to bind the
              Parties.
            </p>
            <p className="mt-4 text-gray-700">
              <strong>Assignment:</strong> Neither Party may assign this
              Agreement without prior written consent from the other Party. Any
              unauthorized assignment, whether by operation of law, court order,
              or other means, shall be void and unenforceable.
            </p>
            <p className="mt-4 text-gray-700">
              <strong>Relationship of the Parties:</strong> Nothing in this
              Agreement creates or implies any partnership, agency, joint
              venture, trust, or employer-employee relationship between the
              Parties. Neither Party may make representations or undertake
              obligations on behalf of the other without explicit authorization.
            </p>
          </section>

          <section className="mt-8">
            <h2 className="text-2xl font-semibold text-gray-900">
              19. Notice Clause
            </h2>
            <p className="mt-4 text-gray-700">
              <strong>Mode of Communication:</strong> All notices, demands, or
              other communications under this Agreement shall be:
            </p>
            <ul className="list-inside list-disc mt-4 text-gray-700">
              <li>Delivered in writing and sent personally,</li>
              <li>Sent by prepaid post with recorded delivery, or</li>
              <li>
                Sent via email to the designated email address:{" "}
                <strong>support@habitatplush.com</strong>.
              </li>
            </ul>
            <p className="mt-4 text-gray-700">
              <strong>Service of Notice:</strong> Unless proven otherwise,
              notices shall be deemed to have been duly served:
            </p>
            <ul className="list-inside list-disc mt-4 text-gray-700">
              <li>Upon personal delivery, at the time of delivery.</li>
              <li>
                If sent by post, upon receipt of recorded delivery confirmation.
              </li>
              <li>In the case of email, upon receipt of the transmission.</li>
            </ul>
          </section>

          <section className="mt-8">
            <h2 className="text-2xl font-semibold text-gray-900">
              20. Support Services Clause
            </h2>
            <p className="mt-4 text-gray-700">
              All support services under this Agreement shall be provided
              electronically and directed to the designated email address:{" "}
              <strong>support@habitatplush.com</strong>.
            </p>
          </section>
        </div>
      </div>

      <Footer />
    </>
  );
};

export default Terms;
